# Fase 1: EDA

In [36]:
# Importamos librerías necesarias
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer 
from sklearn.experimental import enable_iterative_imputer 
from sklearn.impute import IterativeImputer 
from sklearn.impute import KNNImputer 
pd.set_option("display.max_columns", None)

In [37]:
df_hr = pd.read_csv("hr.csv")

In [38]:
def exploracion_inicial(df,name="dataframe"):
    print(f"El dataframe '{name}' tiene {df.shape[0]} filas y {df.shape[1]} columnas.")
    display(df.head(2))
    print("="*150)
    display(df.tail(2))
    print("="*150)
    display(df.sample(2))
    print("="*150)
    print(f"Listamos abajo el conteo de no-nulos junto con el tipo de dato:")
    print("="*150)
    print(df.info())
    print("="*150)

In [39]:
exploracion_inicial(df_hr, "df_hr")

El dataframe 'df_hr' tiene 1474 filas y 35 columnas.

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0

======================================================================================================================================================

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1472,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,4,Male,58,1,1,hUMAN rESOURCES,3.0,Married,1555.0,11585,1,Y,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0
1473,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,rESEARCH sCIENTIST,1.0,Divorced,9724.0,18787,2,Y,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0

======================================================================================================================================================

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
940,39.0,Yes,Travel_Rarely,360,Research & Development,23,3,Medical,1,1310,3,Male,93,3,1,rESEARCH sCIENTIST,1.0,Single,3904.0,22154,0,Y,No,13,3,1,80.0,0,6,2.0,3,5,2,0,3.0
87,51.0,No,Travel_Rarely,432,Research & Development,9,4,Life Sciences,1,116,4,Male,96,3,1,lABORATORY tECHNICIAN,4.0,Married,2075.0,18725,3,Y,No,23,4,2,80.0,2,10,4.0,3,4,2,0,3.0

======================================================================================================================================================
Listamos abajo el conteo de no-nulos junto con el tipo de dato:
======================================================================================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1401 non-null   float64
 1   Attrition                 1474 non-null   str
 2   BusinessTravel            1357 non-null   str
 3   DailyRate                 1474 non-null   int64
 4   Department                1445 non-null   str
 5   DistanceFromHome          1474 non-null   int64
 6   Education                 1474 non-null   int64
 7   EducationField            1416 non-null   str
 8   EmployeeCount             1474 non-null   int64
 9   EmployeeNumber            1474 non-null   int64
 10  EnvironmentSatisfaction   1474 non-null   int64
 11  Gender                    1474 non-null   str
 12  HourlyRate                1474 non-null   int64
 13  JobInvolvement            1474 non-null   int64
 14  JobLevel                  1474 non-null   int64
 15  JobRole                   1474 non-null   str
 16  JobSatisfaction           1445 non-null   float64
 17  MaritalStatus             1342 non-null   str
 18  MonthlyIncome             1460 non-null   float64
 19  MonthlyRate               1474 non-null   int64
 20  NumCompaniesWorked        1474 non-null   int64
 21  Over18                    1474 non-null   str
 22  OverTime                  1430 non-null   str
 23  PercentSalaryHike         1474 non-null   int64
 24  PerformanceRating         1474 non-null   int64
 25  RelationshipSatisfaction  1474 non-null   int64
 26  StandardHours             1310 non-null   float64
 27  StockOptionLevel          1474 non-null   int64
 28  TotalWorkingYears         1474 non-null   int64
 29  TrainingTimesLastYear     1386 non-null   float64
 30  WorkLifeBalance           1474 non-null   int64
 31  YearsAtCompany            1474 non-null   int64
 32  YearsInCurrentRole        1474 non-null   int64
 33  YearsSinceLastPromotion   1474 non-null   int64
 34  YearsWithCurrManager      1326 non-null   float64
dtypes: float64(6), int64(20), str(9)
memory usage: 403.2 KB
None
======================================================================================================================================================

Homogeneizar nombre de las columnas (letras en minuscula e intentar separar palabras con guion bajo )

* Age: tenemos que cambiar de float a int. Y tenemos nulos. 
* Attrition: Cambiar de str a boleano. Y no hay nulos.
* Business travel: Hay nulos. Tipo de dato correcto.
* Departamento: Hay nulos. Tipo dato correcto.
* Education field: Hay nulos. Tipo de dato correcto. 
* Employeecount: La podremos borrar seguramente (no nos da info)
* Employee number: Podemos cambiar de int a str (sirve como ID, no hacemos estadistica con el)
* Job satistfaction: cambiar de float a int. Y hay nulos.
* Marital status: Hay nulos.
* Overtime: Podemos pasar de str a boleano. Y hay nulos.
* Standard hours: Hay nulos. La podremos borrar seguramente porque el valor es 80 solo. 
* Training times last year: Pasar de float a int?? Hay nulos.
* Year with current manager: Pasar de float a int. Hay nulsos.

Identificación de valores nulos

In [40]:
df_hr.isnull().sum()

Age                          73
Attrition                     0
BusinessTravel              117
DailyRate                     0
Department                   29
DistanceFromHome              0
Education                     0
EducationField               58
EmployeeCount                 0
EmployeeNumber                0
EnvironmentSatisfaction       0
Gender                        0
HourlyRate                    0
JobInvolvement                0
JobLevel                      0
JobRole                       0
JobSatisfaction              29
MaritalStatus               132
MonthlyIncome                14
MonthlyRate                   0
NumCompaniesWorked            0
Over18                        0
OverTime                     44
PercentSalaryHike             0
PerformanceRating             0
RelationshipSatisfaction      0
StandardHours               164
StockOptionLevel              0
TotalWorkingYears             0
TrainingTimesLastYear        88
WorkLifeBalance               0
YearsAtCompany                0
YearsInCurrentRole            0
YearsSinceLastPromotion       0
YearsWithCurrManager        148
dtype: int64

In [41]:
porcentaje_nulos= (df_hr.isnull().sum() / df_hr.shape[0] * 100).sort_values(ascending=False)
porcentaje_nulos

StandardHours               11.126187
YearsWithCurrManager        10.040706
MaritalStatus                8.955224
BusinessTravel               7.937585
TrainingTimesLastYear        5.970149
Age                          4.952510
EducationField               3.934871
OverTime                     2.985075
JobSatisfaction              1.967436
Department                   1.967436
MonthlyIncome                0.949796
YearsAtCompany               0.000000
WorkLifeBalance              0.000000
YearsInCurrentRole           0.000000
TotalWorkingYears            0.000000
Over18                       0.000000
YearsSinceLastPromotion      0.000000
RelationshipSatisfaction     0.000000
PerformanceRating            0.000000
PercentSalaryHike            0.000000
StockOptionLevel             0.000000
DailyRate                    0.000000
NumCompaniesWorked           0.000000
Attrition                    0.000000
JobRole                      0.000000
JobLevel                     0.000000
JobInvolvement               0.000000
HourlyRate                   0.000000
Gender                       0.000000
EnvironmentSatisfaction      0.000000
EmployeeNumber               0.000000
EmployeeCount                0.000000
Education                    0.000000
DistanceFromHome             0.000000
MonthlyRate                  0.000000
dtype: float64

In [42]:
def descriptive_analysis(df):
    print("NUMÉRICAS")
    display(df.describe(include="number").T)
    print("CATEGÓRICAS")
    display(df.describe(include="object").T)

In [43]:
descriptive_analysis(df_hr)

NUMÉRICAS

,count,mean,std,min,25%,50%,75%,max
Age,1401.0,36.944325,9.105009,18.0,30.00,36.0,43.00,60.0
DailyRate,1474.0,802.702171,403.539530,102.0,465.00,803.0,1157.00,1499.0
DistanceFromHome,1474.0,9.199457,8.104266,1.0,2.00,7.0,14.00,29.0
Education,1474.0,2.911126,1.024267,1.0,2.00,3.0,4.00,5.0
EmployeeCount,1474.0,1.000000,0.000000,1.0,1.00,1.0,1.00,1.0
EmployeeNumber,1474.0,1024.471506,602.421193,1.0,488.75,1020.5,1555.75,2068.0
EnvironmentSatisfaction,1474.0,2.723881,1.093280,1.0,2.00,3.0,4.00,4.0
HourlyRate,1474.0,65.887381,20.310444,30.0,48.00,66.0,83.75,100.0
JobInvolvement,1474.0,2.729986,0.712861,1.0,2.00,3.0,3.00,4.0
JobLevel,1474.0,2.063772,1.106055,1.0,1.00,2.0,3.00,5.0
JobSatisfaction,1445.0,2.728720,1.106409,1.0,2.00,3.0,4.00,4.0
MonthlyIncome,1460.0,6497.448630,4706.059294,1009.0,2909.00,4907.0,8377.00,19999.0
MonthlyRate,1474.0,14328.611940,7120.225285,2094.0,8054.50,14248.5,20465.75,26999.0
NumCompaniesWorked,1474.0,2.688602,2.496443,0.0,1.00,2.0,4.00,9.0
PercentSalaryHike,1474.0,15.206920,3.659274,11.0,12.00,14.0,18.00,25.0
PerformanceRating,1474.0,3.153324,0.360422,3.0,3.00,3.0,3.00,4.0
RelationshipSatisfaction,1474.0,2.713704,1.080338,1.0,2.00,3.0,4.00,4.0
StandardHours,1310.0,80.000000,0.000000,80.0,80.00,80.0,80.00,80.0
StockOptionLevel,1474.0,0.794437,0.851784,0.0,0.00,1.0,1.00,3.0
TotalWorkingYears,1474.0,11.274084,7.785972,0.0,6.00,10.0,15.00,40.0
TrainingTimesLastYear,1386.0,2.797980,1.296882,0.0,2.00,3.0,3.00,6.0
WorkLifeBalance,1474.0,2.761872,0.705625,1.0,2.00,3.0,3.00,4.0
YearsAtCompany,1474.0,6.996608,6.122920,0.0,3.00,5.0,9.00,40.0
YearsInCurrentRole,1474.0,4.221845,3.622032,0.0,2.00,3.0,7.00,18.0
YearsSinceLastPromotion,1474.0,2.183175,3.219356,0.0,0.00,1.0,3.00,15.0
YearsWithCurrManager,1326.0,4.061840,3.517603,0.0,2.00,3.0,7.00,17.0

CATEGÓRICAS

/var/folders/gm/1xfl990x331_z3ks1j4r5f1c0000gn/T/ipykernel_2962/420535483.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include="object").T)

               count unique                     top  freq
Attrition       1474      2                      No  1236
BusinessTravel  1357      3           Travel_Rarely   955
Department      1445      3  Research & Development   941
EducationField  1416      6           Life Sciences   582
Gender          1474      2                    Male   885
JobRole         1474      9        sALES eXECUTIVE    327
MaritalStatus   1342      4                 Married   604
Over18          1474      1                       Y  1474
OverTime        1430      2                      No  1025

In [44]:
def analizar_categorias(df):
    col_cat = df.select_dtypes(include = "object").columns

    for col in col_cat:
        print("=" * 100)
        print(f"Analizamos las categorias de la columna: {col}")
        print("=" * 100)
        print(df[col].unique())

In [45]:
analizar_categorias(df_hr)

====================================================================================================
Analizamos las categorias de la columna: Attrition
====================================================================================================
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
====================================================================================================
Analizamos las categorias de la columna: BusinessTravel
====================================================================================================
<StringArray>
['Travel_Rarely', 'Travel_Frequently', 'Non-Travel', nan]
Length: 4, dtype: str
====================================================================================================
Analizamos las categorias de la columna: Department
====================================================================================================
<StringArray>
['Sales', 'Research & Development', nan, 'Human Resources']
Length: 4, dtype: str
====================================================================================================
Analizamos las categorias de la columna: EducationField
====================================================================================================
<StringArray>
[   'Life Sciences',            'Other',          'Medical',
                nan,        'Marketing', 'Technical Degree',
  'Human Resources']
Length: 7, dtype: str
====================================================================================================
Analizamos las categorias de la columna: Gender
====================================================================================================
<StringArray>
['Female', 'Male']
Length: 2, dtype: str
====================================================================================================
Analizamos las categorias de la columna: JobRole
====================================================================================================
<StringArray>
[          ' sALES eXECUTIVE ',        ' rESEARCH sCIENTIST ',
     ' lABORATORY tECHNICIAN ',    ' mANUFACTURING dIRECTOR ',
 ' hEALTHCARE rEPRESENTATIVE ',                   ' mANAGER ',
      ' sALES rEPRESENTATIVE ',         ' rESEARCH dIRECTOR ',
           ' hUMAN rESOURCES ']
Length: 9, dtype: str
====================================================================================================
Analizamos las categorias de la columna: MaritalStatus
====================================================================================================
<StringArray>
['Single', 'Married', 'Divorced', nan, 'Marreid']
Length: 5, dtype: str
====================================================================================================
Analizamos las categorias de la columna: Over18
====================================================================================================
<StringArray>
['Y']
Length: 1, dtype: str
====================================================================================================
Analizamos las categorias de la columna: OverTime
====================================================================================================
<StringArray>
['Yes', 'No', nan]
Length: 3, dtype: str

/var/folders/gm/1xfl990x331_z3ks1j4r5f1c0000gn/T/ipykernel_2962/1697058440.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  col_cat = df.select_dtypes(include = "object").columns

* Business travel: Cambiar Non-Travel por Non_Travel
* Job role: hacer capitalize
* Marital: corregir "marreid"

# Fase 2: Transformación de datos

In [46]:
df_hr.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

## Estandarizamos nombre de las columnas

In [47]:
# Homegeneizar nombre de columnas (teniendo en cuenta que vamos a borrar la columna "Over18")

def estandarizar_nombre(nombre):
    resultado = ""
    for i, letra in enumerate(nombre):
        # Si la letra es mayúscula y no es la primera, ponemos un "_"
        if letra.isupper() and i > 0:
            resultado += "_" + letra.lower()
        else:
            resultado += letra.lower()
    return resultado

# Aplicamos el cambio a las columnas:
df_hr.columns = [estandarizar_nombre(col) for col in df_hr.columns]

print(df_hr.columns)

Index(['age', 'attrition', 'business_travel', 'daily_rate', 'department',
       'distance_from_home', 'education', 'education_field', 'employee_count',
       'employee_number', 'environment_satisfaction', 'gender', 'hourly_rate',
       'job_involvement', 'job_level', 'job_role', 'job_satisfaction',
       'marital_status', 'monthly_income', 'monthly_rate',
       'num_companies_worked', 'over18', 'over_time', 'percent_salary_hike',
       'performance_rating', 'relationship_satisfaction', 'standard_hours',
       'stock_option_level', 'total_working_years', 'training_times_last_year',
       'work_life_balance', 'years_at_company', 'years_in_current_role',
       'years_since_last_promotion', 'years_with_curr_manager'],
      dtype='str')

## Corregimos valores de columnas categóricas

* Business travel: Cambiar Non-Travel por Non_Travel
* Job role: hacer capitalize
* Marital: corregir "marreid"

In [61]:
def limpiar_categoricas(df):
    
    cols = df.select_dtypes(include="object").columns
    
    for col in cols:
        df[col] = df[col].str.strip().str.title().str.replace("-","_")
        if col == "marital_status":
            df[col] = df[col].str.replace('Marreid','Married')

    return df

In [62]:
limpiar_categoricas(df_hr)

/var/folders/gm/1xfl990x331_z3ks1j4r5f1c0000gn/T/ipykernel_2962/1791164369.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cols = df.select_dtypes(include="object").columns

,age,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,employee_count,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,monthly_rate,num_companies_worked,over18,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,standard_hours,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0
2,37.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3.0,Single,2090.0,2396,6,Y,Yes,15,3,2,NaN,0,7,3.0,3,0,0,0,0.0
3,33.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3.0,Married,2909.0,23159,1,Y,Yes,11,3,3,80.0,0,8,3.0,3,8,7,3,0.0
4,27.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2.0,Married,3468.0,16632,9,Y,No,12,3,4,80.0,1,6,3.0,3,2,2,2,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1469,34.0,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,2,Male,82,4,2,Laboratory Technician,3.0,Married,4404.0,10228,2,Y,No,12,3,1,NaN,0,6,3.0,4,4,3,1,2.0
1470,28.0,No,Travel_Rarely,866,Sales,5,3,Medical,1,1469,4,Male,84,3,2,Sales Executive,1.0,Single,8463.0,23490,0,Y,No,18,3,4,NaN,0,6,4.0,3,5,4,1,NaN
1471,53.0,No,Travel_Rarely,1084,Research & Development,13,2,Medical,1,250,4,Female,57,4,2,Manufacturing Director,1.0,Divorced,4450.0,26250,1,Y,No,11,3,3,NaN,2,5,3.0,3,4,2,1,3.0
1472,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,4,Male,58,1,1,Human Resources,3.0,Married,1555.0,11585,1,Y,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0
1473,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,Research Scientist,1.0,Divorced,9724.0,18787,2,Y,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0

In [63]:
analizar_categorias(df_hr)
# Para comprobar que se han realizado los cambios correctamente

====================================================================================================
Analizamos las categorias de la columna: attrition
====================================================================================================
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
====================================================================================================
Analizamos las categorias de la columna: business_travel
====================================================================================================
<StringArray>
['Travel_Rarely', 'Travel_Frequently', 'Non_Travel', nan]
Length: 4, dtype: str
====================================================================================================
Analizamos las categorias de la columna: department
====================================================================================================
<StringArray>
['Sales', 'Research & Development', nan, 'Human Resources']
Length: 4, dtype: str
====================================================================================================
Analizamos las categorias de la columna: education_field
====================================================================================================
<StringArray>
[   'Life Sciences',            'Other',          'Medical',
                nan,        'Marketing', 'Technical Degree',
  'Human Resources']
Length: 7, dtype: str
====================================================================================================
Analizamos las categorias de la columna: gender
====================================================================================================
<StringArray>
['Female', 'Male']
Length: 2, dtype: str
====================================================================================================
Analizamos las categorias de la columna: job_role
====================================================================================================
<StringArray>
[          'Sales Executive',        'Research Scientist',
     'Laboratory Technician',    'Manufacturing Director',
 'Healthcare Representative',                   'Manager',
      'Sales Representative',         'Research Director',
           'Human Resources']
Length: 9, dtype: str
====================================================================================================
Analizamos las categorias de la columna: marital_status
====================================================================================================
<StringArray>
['Single', 'Married', 'Divorced', nan]
Length: 4, dtype: str
====================================================================================================
Analizamos las categorias de la columna: over18
====================================================================================================
<StringArray>
['Y']
Length: 1, dtype: str
====================================================================================================
Analizamos las categorias de la columna: over_time
====================================================================================================
<StringArray>
['Yes', 'No', nan]
Length: 3, dtype: str

/var/folders/gm/1xfl990x331_z3ks1j4r5f1c0000gn/T/ipykernel_2962/1697058440.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  col_cat = df.select_dtypes(include = "object").columns

## Cambiar tipos de datos

## Imputación de nulos

## Decidir qué columnas no nos aportan información